language: rust
cache: cargo
dist: trusty
sudo: false
os:
- linux
- osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libusb-1.0-0
    - libusb-1.0-0-dev
    - pkg-config

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable
  - 1.26.2

before_script:
- export PATH=$PATH:~/.cargo/bin
- "./travis-helper.sh install_deps"

# Run the multiple tests.
script:
- "./travis-helper.sh build"
- "./travis-helper.sh package"
- "./travis-helper.sh test"
- "./travis-helper.sh clippy_run"
- "./travis-helper.sh fmt_run"

# Upload code coverage report and documentation.
after_success:
- "./travis-helper.sh upload_code_coverage"
- "./travis-helper.sh upload_documentation"

notifications:
  email:
    on_success: change
    on_failure: always
