[package]
name = "fel-cli"
version = "0.1.0"
authors = ["Razican <razican@protonmail.ch>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/aw-fel-rs"
description = """
CLI tools for dealing with Allwinner devices in FEL mode, in pure Rust.
"""
keywords = ["arm", "sunxi", "allwinner", "fel"]

[dependencies]
error-chain = "0.7"
libusb = "0.3"
aw-fel = "0.1"
clap = "2.19"
ansi_term = "0.9"
